### ISSUE TITLE
Middleware not logging bodies if unhandled exception occurs downstream

### ISSUE THREAD

**Issue by jcoeltjen** [matthiasguentert/azure-appinsights-logger#22]
Hi, 
thanks a lot for this very helpful extension!
I already use it in multiple projects, but I am missing on crucial feature: Logging of request bodies of failing requests (500 responses).

The middleware does not log any request or response bodies if any unhandled exception occurs downstream.
But for us especially in these cases we would love to have at least the request body available in application insights for further debugging.

The extension currently registers a middleware that does **not** catch and handle all exceptions.
For the feature I am missing I would like to implement a different behavior, so that if other middleware handlers or downstream processing fails the error is caught, the request telemetry created and rethrown.

This might create unwanted side effects for users who already have some error handling middleware in place, therefore this feature would be disabled by default.

In hope that this is a feature not only helpful for me, I will try to prepare a corresponding PR for discussing this further.

**Comment by matthiasguentert** [comment]
Hi, and thank you for the feedback and pull request. Always appreciated. 

I think the app insights logging middleware would need to run as early as possible in the pipeline, just like the [ExceptionHandlerMiddleware](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs), so that it can catch unhandled exceptions. And just like you stated, to prevent side effects, the user needs to be able to toggle the feature on and off. 

I'll take a closer look and extend your PR.

**Comment by jcoeltjen** [comment]
I can also have a look into putting this behind a guard clause.
Should be an easy fix.

Do you also want to change the way the service registers the middleware? The ensure that is registered as one of the first middlewares? Currently this would be controlled by the user and when the user decides to register the appinsights logger.

**Comment by matthiasguentert** [comment]
> I can also have a look into putting this behind a guard clause.
Should be an easy fix.

Great! Always happy to receive PRs

> Do you also want to change the way the service registers the middleware? The ensure that is registered as one of the first middlewares? Currently this would be controlled by the user and when the user decides to register the appinsights logger.

How would you solve this?

**Comment by jcoeltjen** [comment]
> > I can also have a look into putting this behind a guard clause.
> > Should be an easy fix.
> 
> Great! Always happy to receive PRs

I will try to add this today, any preferences on the name the configuration parameter for this?
> 
> > Do you also want to change the way the service registers the middleware? The ensure that is registered as one of the first middlewares? Currently this would be controlled by the user and when the user decides to register the appinsights logger.
> 
> How would you solve this?

To be honest I would not solve it at all and keep the order to the user.
 Idea-wise it might be possible to hook into host startup and reorder them there. But from my perspective this introduces too much fairy dust and magic into the startup process. This could lead so some very hard to debug errors for users who have complex setups.

**Comment by matthiasguentert** [comment]
Thank you for the pull request. I'll do some unrelated cleanups and then prepare a release!
