### ISSUE TITLE
Add the ability to hide sensitive information

### ISSUE THREAD

**Issue by Toumash** [matthiasguentert/azure-appinsights-logger#8]
Based on the [stackoverflow answer adjacent to the repo's author](https://stackoverflow.com/a/53776460/3711660) can we add the ability to filter out the sensitive json properties?
I could be just a simple `Func` or `List<string>` to filter out properties like `password`, `base64Content`.
It could be regex

```
var sensitiveProperties =new List<string>() { "password","sensitive.*" }
```

If that's something nice to have in this project, let me know if you would like to see a PR for that

**Comment by crhistianramirez** [comment]
That seems pretty sensible. For default things to scrub:
1. A regex for anything that looks like a credit card
2. Properties that match or contain any of the following keywords:
    * password
   * secret
   * passwd
   * api_key
   * access_token
   * accessToken
   * auth
   * credentials
   * mysql_pwd

It might also be worthwhile to replace the masked content with `***MASKED***` or `***REDACTED***` to avoid any confusion for someone viewing the logs that wasn't aware of the masking behavior.

I do think exposing something like a "preLogging" function would be helpful not only for this use case but also for things like reducing "noisy" log payloads.

**Comment by matthiasguentert** [comment]
Excellent ideas! 

> 1. A regex for anything that looks like a credit card
> 2. Properties that match or contain any of the following keywords:
>    
>    * password
>    * secret
>    * passwd
>    * api_key
>    * access_token
>    * accessToken
>    * auth
>    * credentials
>    * mysql_pwd

I would prepare a list with default keywords and regex patterns to look out for, but at the same time give the user the ability to add their own. 

> 1. It might be worthwhile to replace the masked content with `***MASKED***` or `***REDACTED***` to avoid any confusion for someone viewing the logs that wasn't aware of the masking behavior.

Agreed!

> 2. Besides clearly sensitive information I can also see people wanting to hide PII (personal identifiable information) things like FirstName, LastName, etc. That probably wouldn't be something enabled by default but I could imagine it being a common enough need that we should make it an easy add via configuration.

There alright might be a library out there for PII scrubbing, so the wheel doesn't have to be reinvented. 

> 3. Exposing something like a "preLogging" function would be helpful not only for this use case but also for things like reducing "noisy" log payloads.

Could be an extension point based on e.g. `Action<HttpContext> PreLogging`. Is anyone willing to prepare a PR?

**Comment by crhistianramirez** [comment]
I'll give @Toumash the opportunity to take this on as he mentioned interest and brought the issue up but if for whatever reason he is not able to I would gladly prepare a PR.

**Comment by Toumash** [comment]
I think that there are two different problems:
* filtering properties by keys
* filtering/masking data inside (property values) based on some regexes

For the first point im sure its fine, but not for the second one.

I've created something as a starting point:  #9

**Comment by Toumash** [comment]
I think that there are two different problems:
* filtering properties by keys
* filtering/masking data inside (property values) based on some regexes

For the first point im sure its fine, but the second is much more complicated.

I've created something as a starting point:  #9 
For me its enough to use

**Comment by matthiasguentert** [comment]
https://github.com/matthiasguentert/azure-appinsights-logger/pull/19
